# -*- coding: utf-8 -*-
"""taskk1(2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#task 1 (2)
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/input1(2).txt","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/output1(2).txt","w")
x =input_file.readline().split()
N= int(x[0])
S = int(x[1])

num = input_file.readline().split()

def findtarget2(N,S): #time complexcity O(n)
  i,j=0,(N-1)
  while i < j:
    if int(num[i]) + int(num[j]) == S :
        output_file.write(f"{i+1}  {j+1}")
        return

    if int(num[i]) + int(num[j]) > S :
      j = j-1
    elif int(num[i]) + int(num[j]) < S :
      i+=1
  output_file.write(f"IMPOSSIBLE")
  return

findtarget2(N,S)
input_file.close()
output_file.close()