# -*- coding: utf-8 -*-
"""Task2(2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#Task2(2)
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/input2(2).txt","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/output2(2).txt","w")
N = int(input_file.readline())
Nlst = input_file.readline().split()
M = int(input_file.readline())
Mlst = input_file.readline().split()
sortlst=[]
i,j=0,0
while i < N and j< M:
  if int(Nlst[i]) > int(Mlst[j]):
    sortlst.append((Mlst[j]))
    j+=1
  elif int(Nlst[i]) < int(Mlst[j]):
    sortlst.append((Nlst[i]))
    i+=1
  elif int(Nlst[i]) == int(Mlst[j]):
    sortlst.append((Nlst[i]))
    sortlst.append((Mlst[j]))
    i+=1
    j+=1
if i < N:
  sortlst.extend(Nlst[i::])
else:
  sortlst.extend(Mlst[j::])

output_file.write(f'{" ".join(sortlst)}')
input_file.close()
output_file.close()