# -*- coding: utf-8 -*-
"""#Task1 a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#Task1 a
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/input1a","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/output1a","w")
num = input_file.readline()
T = int(num)

for i in range(T):
  num= input_file.readline()
  num = int(num.rstrip())
  if num%2 == 0 :
    output_file.write(f"{num} is an Even number.\n")
  else:
    output_file.write(f"{num} is an Odd number.\n")

input_file.close()
output_file.close()