# -*- coding: utf-8 -*-
"""Task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#Task4
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/input4","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/output4","w")
num = input_file.readline()
T = int(num)
train=[]
loc=[]
time=[]
for line in input_file:
  temp=line.split()
  train.append(temp[0])
  loc.append(temp[4])
  time.append(temp[6])

for i in range(T):
  idx= i
  for j in range(i+1,T):
    if train[idx] > train[j] or (train[idx]==train[j] and time[idx] < time[j]):
      idx=j
  train[i],train[idx]=train[idx],train[i]
  loc[i],loc[idx]=loc[idx],loc[i]
  time[i],time[idx]=time[idx],time[i]

for i in range(T):
  output_file.write(f'{train[i]} will departure for {loc[i]} at {time[i]}\n')

input_file.close()
output_file.close()