# -*- coding: utf-8 -*-
"""#Task1 b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#task1 b
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/input1b","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/output1b","w")
num = input_file.readline()
T = int(num)
for i in range(T):
  x = input_file.readline()
  r =x.split()
  if r[2]=="+":
    calc= int(r[1])+int(r[3])
  elif r[2]=="-":
    calc= int(r[1])-int(r[3])
  elif r[2]=="/":
    calc= int(r[1])/int(r[3])
  elif r[2]=="*":
    calc= int(r[1])*int(r[3])
  output_file.write(f"The result of {int(r[1])} {r[2]} {int(r[3])} is {calc}\n")
input_file.close()
output_file.close()