# -*- coding: utf-8 -*-
"""Task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#Task3

input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/input3","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/output3","w")
num = input_file.readline()
T = int(num)
if  1 <= T <= 1000:
  id = input_file.readline().split()
  marks =input_file.readline().split()

def selectionsort(Id , Marks, T):


  for i in range (T):
    idx = i
    for j in range(i+1,T):
      if Marks[idx] < Marks[j] or (Marks[idx] == Marks[j] and Id[idx] > Id[j]):
        idx = j
    Marks[idx],Marks[i] = Marks[i],Marks[idx]
    Id[idx],Id[i]= Id[i],Id[idx]

  for k in range(T):
        output_file.write(f'ID: {Id[k]} Marks: {Marks[k]}\n')

  return

selectionsort(id , marks, T)
input_file.close()
output_file.close()