# -*- coding: utf-8 -*-
"""Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#Task 2
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/input2","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/result/output2","w")
num = input_file.readline()
T = int(num)
def bubbleSort(arr):
  flag = 0
  for i in range(len(arr)-1):

    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        flag += 1

    if flag == 0:     #this is 0 means that the loop has run for 1 time, the array is sorted.
      break           #we're breaking the loop only when the array is sorted for best case scenario.
  return arr
arr = input_file.readline().split()
arr1= bubbleSort(arr)
for i in arr1:
  output_file.write(i+" ")
input_file.close()
output_file.close()