# -*- coding: utf-8 -*-
"""taskk1(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12L-2jUx0iufW0QOpYy0uMTNwU9XEExWg
"""

#taskk1(1)
input_file = open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/input1(1).txt","r")
output_file =open("/content/drive/MyDrive/bracU/5th semester/CSE221/LAB/Lab02/output1(1).txt","w")
x =input_file.readline().split()
N= int(x[0])
S = int(x[1])
# if (1 <= N <= 10**5 and 1 <= S <= 10**9 ) is False:
num = input_file.readline().split()

def findtarget(N,S): #time complexcity O(n^2)
  for i in range(N):

    for j in range(i+1,N):
      if int(num[i]) + int(num[j]) == S :
        output_file.write(f"{i+1}  {j+1}")
        return

  output_file.write(f"IMPOSSIBLE")
  return

findtarget(N,S)
input_file.close()
output_file.close()